# Generated by Django 5.2 on 2025-05-08 06:05

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', null=True, upload_to='avatars', validators=[tracker.models.validate_image_size]),
        ),
    ]
