# Generated by Django 5.2 on 2025-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_genre_movie_profile_favorites_profile_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
