# Generated by Django 5.2 on 2025-05-26 10:00

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='', validators=[tracker.models.validate_image_size]),
        ),
    ]
